# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSAchat(object):
    def setupUi(self, RSAchat):
        RSAchat.setObjectName("RSAchat")
        RSAchat.resize(500, 600)
        self.centralwidget = QtWidgets.QWidget(RSAchat)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame_main.setStyleSheet("background-color: #393E46;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.write_msg = QtWidgets.QFrame(self.frame_main)
        self.write_msg.setGeometry(QtCore.QRect(25, 515, 450, 60))
        self.write_msg.setStyleSheet("background-color: #222831;\n"
"border-radius: 30%")
        self.write_msg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.write_msg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.write_msg.setObjectName("write_msg")
        self.send_btn = QtWidgets.QPushButton(self.write_msg)
        self.send_btn.setGeometry(QtCore.QRect(390, 10, 41, 40))
        self.send_btn.setStyleSheet("background-color: #00ADB5;\n"
"border: none;\n"
"border-radius: 20%;\n"
"color: #eeeeee;\n"
"font-size: 18px;\n"
"font-weight: 300;")
        self.send_btn.setObjectName("send_btn")
        self.send_input = QtWidgets.QLineEdit(self.write_msg)
        self.send_input.setGeometry(QtCore.QRect(20, 10, 350, 40))
        self.send_input.setStyleSheet("color: #fff;\n"
"font-size: 20px;")
        self.send_input.setObjectName("send_input")
        self.frame_menu = QtWidgets.QFrame(self.frame_main)
        self.frame_menu.setGeometry(QtCore.QRect(0, 0, 500, 85))
        self.frame_menu.setStyleSheet("background-color: #222831;")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.status_connect = QtWidgets.QFrame(self.frame_menu)
        self.status_connect.setGeometry(QtCore.QRect(25, 30, 30, 30))
        self.status_connect.setAutoFillBackground(False)
        self.status_connect.setStyleSheet("background-color: #9ADE7B;\n"
"border-radius: 15px;\n"
"")
        self.status_connect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_connect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_connect.setObjectName("status_connect")
        self.status_disconnect = QtWidgets.QFrame(self.frame_menu)
        self.status_disconnect.setGeometry(QtCore.QRect(25, 30, 30, 30))
        self.status_disconnect.setAutoFillBackground(False)
        self.status_disconnect.setStyleSheet("background-color: #FF8F8F;\n"
"border-radius: 15px;\n"
"")
        self.status_disconnect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_disconnect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_disconnect.setObjectName("status_disconnect")
        self.settings_btn = QtWidgets.QPushButton(self.frame_menu)
        self.settings_btn.setGeometry(QtCore.QRect(285, 25, 190, 40))
        self.settings_btn.setStyleSheet("background-color: #00ADB5;\n"
"border: none;\n"
"border-radius: 20%;\n"
"color: #eeeeee;\n"
"font-size: 18px;\n"
"font-weight: 300;")
        self.settings_btn.setObjectName("settings_btn")
        self.msg_plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_main)
        self.msg_plainTextEdit.setGeometry(QtCore.QRect(10, 90, 471, 411))
        self.msg_plainTextEdit.setStyleSheet("border: none;\n"
"color: #fff;\n"
"font-size: 20px;")
        self.msg_plainTextEdit.setObjectName("msg_plainTextEdit")
        self.frame_guide = QtWidgets.QFrame(self.centralwidget)
        self.frame_guide.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame_guide.setStyleSheet("background-color: #393E46;")
        self.frame_guide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_guide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_guide.setObjectName("frame_guide")
        self.guide_text = QtWidgets.QLabel(self.frame_guide)
        self.guide_text.setGeometry(QtCore.QRect(34, 15, 441, 501))
        self.guide_text.setStyleSheet("color: #eeeeee;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"")
        self.guide_text.setWordWrap(True)
        self.guide_text.setObjectName("guide_text")
        self.back_btn = QtWidgets.QPushButton(self.frame_guide)
        self.back_btn.setGeometry(QtCore.QRect(50, 530, 410, 50))
        self.back_btn.setStyleSheet("background-color: #00ADB5;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.frame_connect = QtWidgets.QFrame(self.centralwidget)
        self.frame_connect.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame_connect.setStyleSheet("background-color: #393E46;")
        self.frame_connect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_connect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_connect.setObjectName("frame_connect")
        self.conn_btn = QtWidgets.QPushButton(self.frame_connect)
        self.conn_btn.setGeometry(QtCore.QRect(35, 150, 430, 60))
        self.conn_btn.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.conn_btn.setObjectName("conn_btn")
        self.result_plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_connect)
        self.result_plainTextEdit.setGeometry(QtCore.QRect(35, 240, 431, 111))
        self.result_plainTextEdit.setStyleSheet("color: #fff;\n"
"border: 1px solid grey;\n"
"font-size: 20px;")
        self.result_plainTextEdit.setPlainText("")
        self.result_plainTextEdit.setObjectName("result_plainTextEdit")
        self.guide_btn_2 = QtWidgets.QPushButton(self.frame_connect)
        self.guide_btn_2.setGeometry(QtCore.QRect(35, 390, 430, 60))
        self.guide_btn_2.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.guide_btn_2.setObjectName("guide_btn_2")
        self.back_btn_3 = QtWidgets.QPushButton(self.frame_connect)
        self.back_btn_3.setGeometry(QtCore.QRect(50, 500, 410, 50))
        self.back_btn_3.setStyleSheet("background-color: #00ADB5;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"")
        self.back_btn_3.setObjectName("back_btn_3")
        self.ip_input = QtWidgets.QLineEdit(self.frame_connect)
        self.ip_input.setGeometry(QtCore.QRect(30, 20, 440, 40))
        self.ip_input.setStyleSheet("background-color: #EEEEEE;\n"
"color: #393E46;\n"
"font-size: 26px;\n"
"border-radius: 10%;")
        self.ip_input.setMaxLength(15)
        self.ip_input.setObjectName("ip_input")
        self.port_input = QtWidgets.QLineEdit(self.frame_connect)
        self.port_input.setGeometry(QtCore.QRect(30, 80, 440, 40))
        self.port_input.setStyleSheet("background-color: #EEEEEE;\n"
"color: #393E46;\n"
"font-size: 26px;\n"
"border-radius: 10%;")
        self.port_input.setMaxLength(5)
        self.port_input.setObjectName("port_input")
        self.frame_generate = QtWidgets.QFrame(self.centralwidget)
        self.frame_generate.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame_generate.setStyleSheet("background-color: #393E46;")
        self.frame_generate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_generate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_generate.setObjectName("frame_generate")
        self.result_plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_generate)
        self.result_plainTextEdit_2.setGeometry(QtCore.QRect(35, 240, 431, 111))
        self.result_plainTextEdit_2.setStyleSheet("color: #fff;\n"
"border: 1px solid grey;\n"
"font-size: 20px;")
        self.result_plainTextEdit_2.setPlainText("")
        self.result_plainTextEdit_2.setObjectName("result_plainTextEdit_2")
        self.guide_btn_3 = QtWidgets.QPushButton(self.frame_generate)
        self.guide_btn_3.setGeometry(QtCore.QRect(35, 390, 430, 60))
        self.guide_btn_3.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.guide_btn_3.setObjectName("guide_btn_3")
        self.back_btn_4 = QtWidgets.QPushButton(self.frame_generate)
        self.back_btn_4.setGeometry(QtCore.QRect(50, 500, 410, 50))
        self.back_btn_4.setStyleSheet("background-color: #00ADB5;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"")
        self.back_btn_4.setObjectName("back_btn_4")
        self.generate_btn = QtWidgets.QPushButton(self.frame_generate)
        self.generate_btn.setGeometry(QtCore.QRect(35, 150, 430, 60))
        self.generate_btn.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.generate_btn.setObjectName("generate_btn")
        self.ip_input_2 = QtWidgets.QLineEdit(self.frame_generate)
        self.ip_input_2.setGeometry(QtCore.QRect(30, 20, 440, 40))
        self.ip_input_2.setStyleSheet("background-color: #EEEEEE;\n"
"color: #393E46;\n"
"font-size: 26px;\n"
"border-radius: 10%;")
        self.ip_input_2.setInputMask("")
        self.ip_input_2.setMaxLength(15)
        self.ip_input_2.setObjectName("ip_input_2")
        self.port_input_2 = QtWidgets.QLineEdit(self.frame_generate)
        self.port_input_2.setGeometry(QtCore.QRect(30, 80, 440, 40))
        self.port_input_2.setStyleSheet("background-color: #EEEEEE;\n"
"color: #393E46;\n"
"font-size: 26px;\n"
"border-radius: 10%;")
        self.port_input_2.setMaxLength(5)
        self.port_input_2.setObjectName("port_input_2")
        self.frame_settings = QtWidgets.QFrame(self.centralwidget)
        self.frame_settings.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame_settings.setStyleSheet("background-color: #393E46;")
        self.frame_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings.setObjectName("frame_settings")
        self.goconn_btn = QtWidgets.QPushButton(self.frame_settings)
        self.goconn_btn.setGeometry(QtCore.QRect(40, 50, 430, 60))
        self.goconn_btn.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.goconn_btn.setObjectName("goconn_btn")
        self.gogenerate_btn = QtWidgets.QPushButton(self.frame_settings)
        self.gogenerate_btn.setGeometry(QtCore.QRect(40, 175, 430, 60))
        self.gogenerate_btn.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.gogenerate_btn.setObjectName("gogenerate_btn")
        self.guide_btn = QtWidgets.QPushButton(self.frame_settings)
        self.guide_btn.setGeometry(QtCore.QRect(40, 300, 430, 60))
        self.guide_btn.setStyleSheet("background-color: #222831;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 700;\n"
"font-size: 28px;")
        self.guide_btn.setObjectName("guide_btn")
        self.back_btn_2 = QtWidgets.QPushButton(self.frame_settings)
        self.back_btn_2.setGeometry(QtCore.QRect(50, 500, 410, 50))
        self.back_btn_2.setStyleSheet("background-color: #00ADB5;\n"
"border-radius: 20%;\n"
"border: none;\n"
"color: #EEEEEE;\n"
"font-weight: 500;\n"
"font-size: 28px;\n"
"")
        self.back_btn_2.setObjectName("back_btn_2")
        self.frame_guide.raise_()
        self.frame_settings.raise_()
        self.frame_connect.raise_()
        self.frame_generate.raise_()
        self.frame_main.raise_()
        RSAchat.setCentralWidget(self.centralwidget)

        self.retranslateUi(RSAchat)
        QtCore.QMetaObject.connectSlotsByName(RSAchat)

    def retranslateUi(self, RSAchat):
        _translate = QtCore.QCoreApplication.translate
        RSAchat.setWindowTitle(_translate("RSAchat", "RSAchat"))
        RSAchat.setWindowIcon(QtGui.QIcon('assets\\icon.png'))
        self.send_btn.setText(_translate("RSAchat", ">"))
        self.settings_btn.setText(_translate("RSAchat", "настройки ->"))
        self.msg_plainTextEdit.setPlainText(_translate("RSAchat", "\n"
""))
        self.guide_text.setText(_translate("RSAchat", "1. Необходимо сгенерировать два файла (кнопка сгенерировать ключи)\n"
"\n"
" 2. Заходим в директорию, куда был установлен чат.\n"
"\n"
" 3. Файл send_to_friend необходимо отправить вашему собеседнику\n"
"\n"
" 4. На одном из компьютеров (или на другом) необходимо запустить сервер (находится в той же директории, что и чат).\n"
"\n"
" 5. Пользователь, на чьём компьютере запущен сервер, должен отправить папку data (в той же директории, что и сервер) собеседнику.\n"
"\n"
" 6. Получив папку data, пользователь помещает её в директорию, куда вы устанавливали чат, а заеам нажать на кнопку Подключиться, после чего произойдёт подключение."))
        self.back_btn.setText(_translate("RSAchat", "<- Назад"))
        self.conn_btn.setText(_translate("RSAchat", "Подключиться"))
        self.guide_btn_2.setText(_translate("RSAchat", "Инструкция"))
        self.back_btn_3.setText(_translate("RSAchat", "<- Назад"))
        self.guide_btn_3.setText(_translate("RSAchat", "Инструкция"))
        self.back_btn_4.setText(_translate("RSAchat", "<- Назад"))
        self.generate_btn.setText(_translate("RSAchat", "Сгенерировать файлы"))
        self.goconn_btn.setText(_translate("RSAchat", "Подключиться"))
        self.gogenerate_btn.setText(_translate("RSAchat", "Сгенерировать файлы"))
        self.guide_btn.setText(_translate("RSAchat", "Инструкция"))
        self.back_btn_2.setText(_translate("RSAchat", "<- Назад"))

        self.guide_btn.clicked.connect(lambda: self.frame_guide.raise_())
        self.guide_btn_2.clicked.connect(lambda: self.frame_guide.raise_())
        self.guide_btn_3.clicked.connect(lambda: self.frame_guide.raise_())
        self.settings_btn.clicked.connect(lambda: self.frame_settings.raise_())
        self.goconn_btn.clicked.connect(lambda: self.frame_connect.raise_())
        self.gogenerate_btn.clicked.connect(lambda: self.frame_generate.raise_())
        self.back_btn.clicked.connect(lambda: self.frame_guide.lower())
        self.back_btn_2.clicked.connect(lambda: self.frame_settings.lower())
        self.back_btn_3.clicked.connect(lambda: self.frame_connect.lower())
        self.back_btn_4.clicked.connect(lambda: self.frame_generate.lower())


        self.send_btn.setEnabled(False)
        self.msg_plainTextEdit.setReadOnly(True)
        self.result_plainTextEdit.setReadOnly(True)
        self.result_plainTextEdit_2.setReadOnly(True)
        self.msg_plainTextEdit.appendPlainText('Для начала сгененерируйте файлы. Далее следуйте иструкции. (Все это находится в настройках)')
        self.ip_input.setPlaceholderText("IP сервера...")
        self.ip_input_2.setPlaceholderText("IP сервера...")
        self.port_input.setPlaceholderText("Порт сервера...")
        self.port_input_2.setPlaceholderText("Порт сервера...")